# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b922a5152c027d2270db6ea3df8da7cb8de3297259a716e8defbfddd8dd404261c6b81551e6b67f7f4b4713d41206c9b3b4cd887af6ccbbb8b6436ff9008c82

test:
  secret_key_base: a4b54b4ee5a707e15cfd50b111400be3280fee354633eaec920a245fd1d7ecb7d8c77d8bd9e54f2c47815c15ee4003487cd8d8a849dd6173a26bdab35f64d225

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
